# Generated by Django 3.0.5 on 2020-04-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table='tbl_Agents',
        ),
    ]
